Repository lnsandnkth/CI, pull requests merged in 2022-02, with the labels that each got.

#28 feat - run build task and get build result + logs (Issue/#27)
  src/main/java/com/example/ContinuousIntegrationServer.java
  src/main/java/com/example/Repository.java
Labels: feature, ci#compil

#32 Issue/#12
  src/main/java/com/example/ContinuousIntegrationServer.java
  src/main/java/com/example/database/DatabaseHistory.java
Labels: feature, ci#history

#40 fix - database addInfo build_date (#39)
  src/main/java/com/example/database/Database.java
Labels: bug, ci#history

#43 feat - added link to commit details page on full history page (#42)
  src/main/java/com/example/database/DatabaseHistory.java
Labels: feature, ci#history

#44 fix - delete tmp folder (#37)
  src/main/java/com/example/ContinuousIntegrationServer.java
Labels: bug

#49 tests - added tests for git clone and git checkout (#48)
  src/main/java/com/example/Repository.java
  src/test/java/RepositoryTest.java
Labels: ci#history, u-tests

#53 doc - added Javadoc generation command to gradle and missing document…
  build.gradle
  src/main/java/com/example/Commit.java
  src/main/java/com/example/ContinuousIntegrationServer.java
  src/main/java/com/example/Repository.java
  src/main/java/com/example/database/BuildInfo.java
  src/main/java/com/example/database/Database.java
  src/main/java/com/example/database/DatabaseHistory.java
Labels: documentation

#46 feat - unique names in username list db (Issue/#45)
  src/main/java/com/example/ContinuousIntegrationServer.java
  src/main/java/com/example/database/BuildInfo.java
  src/main/java/com/example/database/Database.java
  src/main/java/com/example/database/DatabaseHistory.java
  src/test/java/DatabaseTest.java
Labels: feature, ci#history

#58 doc - max contributions (#57)
  README.md
Labels: documentation

#56 refactor, feat - refactored build status into BuildStatus enum, added Pending status
  src/main/java/com/example/Commit.java
  src/main/java/com/example/ContinuousIntegrationServer.java
  src/main/java/com/example/PushEvent.java
  src/test/java/TestPostStatus.java
Labels: feature, ci#notif

#59 doc - add the reasons for p+ (#55)
  README.md
Labels: documentation
